# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 54.195.46.71
  become: yes

  tasks:

- name: Call Roles
  hosts: 54.195.46.71
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
